name: Delete branch after merge

on:
  pull_request:
    types: [closed]

jobs:
  deleteBranch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          BRANCH=${{ github.event.pull_request.head.ref }}
          if [ "$BRANCH" != "main" ]; then
            git push origin --delete $BRANCH || echo "Branch $BRANCH not found, skipping deletion."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
